#!/data/data/com.termux/files/usr/bin/bash

x=0
while [ $x -le 7 ]
do
   su -c "chmod 777 /sys/devices/system/cpu/cpu$x/cpufreq/scaling_governor"
   su -c "echo conservative > /sys/devices/system/cpu/cpu$x/cpufreq/scaling_governor"
   x=$(( $x + 1 ))
done

su -c "chmod 777 /sys/class/kgsl/kgsl-3d0/min_clock_mhz"
su -c "echo 305 > /sys/class/kgsl/kgsl-3d0/min_clock_mhz"
su -c "chmod 777 /sys/class/kgsl/kgsl-3d0/devfreq/governor"
su -c "echo powersave > /sys/class/kgsl/kgsl-3d0/devfreq/governor"
su -c "chmod 777 /sys/class/kgsl/kgsl-3d0/default_pwrlevel"
su -c "echo 5 > /sys/class/kgsl/kgsl-3d0/default_pwrlevel"
su -c "echo 0 > /sys/class/kgsl/kgsl-3d0/throttling"

su -c "chmod 777 /sys/block/sda/queue/scheduler"
su -c "echo noop > /sys/block/sda/queue/scheduler"

su -c "pm enable com.android.vending"
su -c "pm enable com.android.deskclock"
su -c "pm enable com.android.providers.downloads"
su -c "pm enable com.facebook.katana"
su -c "pm enable com.android.deskclock"
su -c "pm enable com.lonelycatgames.Xplore"
su -c "pm enable org.telegram.messenger"
su -c "pm enable com.oasisfeng.greenify"
su -c "pm enable com.google.android.youtube"
su -c "pm enable com.topjohnwu.magisk"
su -c "pm enable com.android.bluetooth"
su -c "pm enable com.android.bluetoothmidiservice"
su -c "pm enable com.android.chrome"
su -c "pm enable org.swiftapps.swiftbackup"
su -c "pm enable com.android.camera"
su -c "pm enable com.miHoYo.GenshinImpact"
su -c "pm enable com.garena.game.kgvn"
su -c "pm disable com.jairath.ccaster"
su -c "pm disable com.google.android.play.games"
su -c "pm disable com.vng.pubgmobile"
su -c "pm disable app.greyshirts.firewall"
su -c "pm disable com.twitter.android"
su -c "pm disable free.vpn.unblock.proxy.turbovpn"
su -c "pm disable com.vng.pubgmobile"
su -c "pm disable com.pandavpn.androidproxy"
su -c "pm disable com.android.vpndialogs"
su -c "pm disable com.hellraiser.unitemod"
su -c "pm disable com.forexgaming"
su -c "pm disable com.jairath.tencentig"
su -c "pm disable com.misaki.putri"
su -c "pm disable com.Putri"
su -c "pm enable com.chrome.beta"
su -c "pm disable com.putri.esp"

killall -9 com.miHoYo.GenshinImpact
killall -9 com.garena.game.kgvn

printf 'su -c "echo powersave > /sys/class/kgsl/kgsl-3d0/devfreq/governor"

a=`su -c "cat /sys/class/kgsl/kgsl-3d0/devfreq/governor"`
if [ $a != powersave ]
then
     su -c "sh /storage/emulated/0/Download/ext/temp/bt_powersave"
else
      su -c "am start --user 0 -n org.swiftapps.swiftbackup/org.swiftapps.swiftbackup.intro.IntroActivity"
      su -c "killall -9 com.termux"
fi
' > /storage/emulated/0/Download/ext/temp/bt_powersave

su -c "echo 35 > /proc/sys/vm/swappiness"

printf 'su -c "echo 35 > /proc/sys/vm/swappiness"
a=`su -c "cat /proc/sys/vm/swappiness"`
if [ $a != 35 ]
then
     su -c "sh /storage/emulated/0/Download/ext/temp/bt_swappiness"
else
      echo "•swappiness: 35"
fi
' > /storage/emulated/0/Download/ext/temp/bt_swappiness

a=`su -c "cat /proc/sys/vm/swappiness"`
if [ $a != 35 ]
then
     su -c "sh /storage/emulated/0/Download/ext/temp/bt_swappiness"
else
      echo "•swappiness: 35"
fi

a=`su -c "cat /sys/class/kgsl/kgsl-3d0/devfreq/governor"`
if [ $a != 'powersave' ]
then
     su -c "sh /storage/emulated/0/Download/ext/temp/bt_powersave"
else
      app=`cat /storage/emulated/0/Download/ext/temp/run_app`
      if [ $app = gi ]
	  then
	      su -c "am start --user 0 -n org.swiftapps.swiftbackup/org.swiftapps.swiftbackup.intro.IntroActivity"
      elif [ $app = aov ]
	  then
		  echo ""
	  fi
      rm -rf /storage/emulated/0/Download/ext/temp/bt_swappiness
      rm -rf /storage/emulated/0/Download/ext/temp/bt_powersave
      rm -rf /storage/emulated/0/Download/ext/temp/run_app
      su -c "killall -9 com.termux"
fi
