#!/bin/bash

rm /sdcard/Download/ext/temp/d
ls /sdcard/Download/ext > /sdcard/Download/ext/temp/d
awk -i inplace '!/temp/' /sdcard/Download/ext/temp/d
if [[ -z $(grep '[^[:space:]]' /sdcard/Download/ext/temp/d) ]]
then
	echo "Không có rom đã giải nén!"
else
	x=`wc -l < /sdcard/Download/ext/temp/d`
	echo "DỌN DẸP"
	echo "1. Dọn dẹp rom đơn lẻ"
	echo "2. Dọn dẹp tất cả"
	echo "Nhập số từ 1-2 (nhấn kí tự x để thoát):"
	read b
	
	if [ $b == 1 ]
	then
		clear
		awk '{print NR  ". " $s}' /sdcard/Download/ext/temp/d >> /sdcard/Download/ext/temp/d1
		echo "Rom đã giải nén:"
		cat /sdcard/Download/ext/temp/d1
		rm /sdcard/Download/ext/temp/d1
		echo "Chọn rom đã giải nén cần xóa:"
		echo "Nhập số từ 1-$x: (nhấn kí tự x để thoát)"
		read c
		if [[ $c == x ]]
		then
			echo "Thoát!!"
		else
			sed -n "$c"p /sdcard/Download/ext/temp/d >> /sdcard/Download/ext/temp/rom$c
			rm -rf /sdcard/Download/ext/`cat /sdcard/Download/ext/temp/rom$c`
			rm -rf /sdcard/Download/ext/temp/rom$c
		fi
	elif [ $b == 2 ]
	then
		echo "Xóa ROM:"
		for (( v=1; v<=$x; v++ ))
		do
			sed -n "$v"p /sdcard/Download/ext/temp/d >> /sdcard/Download/ext/temp/rom$v
			echo "[$v/$x] `cat /sdcard/Download/ext/temp/rom$v`"
			rm -rf /sdcard/Download/ext/`cat /sdcard/Download/ext/temp/rom$v`
			echo "Hoàn thành !"
			rm -rf /sdcard/Download/ext/temp/rom$v
		done
	elif [ $b == x ]
	then
		echo "Bỏ qua!!"
	fi
fi
rm /sdcard/Download/ext/temp/d
