#!/data/data/com.termux/files/usr/bin/bash

a=`wget -O - https://github.com/topjohnwu/Magisk/releases | grep "topjohnwu/Magisk/releases/tag/v" | perl -pe 'if(($_)=/([0-9]+([.][0-9]+)+)/){$_.="\n"}' | awk '{if ($1 > max) max=$1}END{print max}'`

b=`find /storage/emulated/0 -maxdepth 1 -name "Magisk-v*" | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/'`

function version {
	echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
}

if [ $(version $a) -gt $(version $b) ]
then
	download_link=https://github.com/topjohnwu/Magisk/releases/download/v$a/Magisk-v$a.apk
	rm /storage/emulated/0/Magisk-v* 2>/dev/null
	wget --no-check-certificate  -P /storage/emulated/0 "$download_link"
	mv /storage/emulated/0/Magisk-v$a.apk /storage/emulated/0/Magisk-v$a.zip
	echo `date +"%r, %a, ngày %d, tháng %m, năm %Y"` >> /storage/emulated/0/Download/ext/temp/log
	echo "•Magisk: v$b --> v$a" >> /storage/emulated/0/Download/ext/temp/log
else
    echo `date +"%r, %a, ngày %d, tháng %m, năm %Y"` >> /storage/emulated/0/Download/ext/temp/log
	echo "•Magisk: Không có cập nhật mới." >> /storage/emulated/0/Download/ext/temp/log
fi

sed -i 's/ PM,/ CH,/g; s/ AM,/ SA,/g; s/ Mon, / thứ Hai, /g; s/ Tue, / thứ Ba, /g; s/ Wed, / thứ Tư, /g; s/ Thur, / thứ Năm, /g; s/ Fri, / thứ Sáu, /g; s/ Sat, / thứ Bảy, /g; s/ Sun, / Chủ nhật, /g' /storage/emulated/0/Download/ext/temp/log