#!/bin/bash
clear
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                   UNPACK ROM ANDROID                       +"
echo "+                        BEACHEAD                            +"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo ""
echo "MENU "
echo "1. Trích xuất rom"
echo "2. Dọn dẹp rom"
echo "3. Hệ thống"
echo "4. Thông tin Kernel"
echo "5. Game"
echo "Nhập số từ 1-5 (nhấn x để thoát):"
read menu

case $menu in
	1)
		echo "Chạy profile kernel: performance"
		sh /sdcard/Download/ext/temp/performance
		bash /sdcard/Download/ext/temp/unpack
		;;
	2)
		echo "Chạy profile kernel: performance"
		sh /sdcard/Download/ext/temp/performance
		bash /sdcard/Download/ext/temp/cleanrom
		;;
	3)
		clear
		sh /sdcard/Download/ext/temp/performance
		echo "HỆ THỐNG"
		echo "1. Tùy biến"
		echo "2. Kiểm tra cập nhật ứng dụng"
		echo "Nhập số từ 1-2 (nhấn x để thoát):"
		read system
		
		case $system in
			1)
				pm disable com.android.apps.tag
				pm disable com.android.backupconfirm
				pm disable com.android.bips
				pm disable com.android.bluetooth
				pm disable com.android.bluetoothmidiservice
				pm disable com.android.bookmarkprovider
				pm disable com.android.calllogbackup
				pm disable com.android.captiveportallogin
				pm disable com.android.cellbroadcastreceiver
				pm disable com.android.certinstaller
				pm disable com.android.egg
				pm disable com.android.emergency
				pm disable com.android.inputmethod.latin
				pm disable com.android.internal.display.cutout.emulation.corner
				pm disable com.android.internal.display.cutout.emulation.double
				pm disable com.android.internal.display.cutout.emulation.tall
				pm disable com.android.internal.systemui.navbar.gestural_extra_wide_back
				pm disable com.android.internal.systemui.navbar.gestural_narrow_back
				pm disable com.android.internal.systemui.navbar.gestural_wide_back
				pm disable com.android.internal.systemui.navbar.threebutton
				pm disable com.android.internal.systemui.navbar.twobutton
				pm disable com.android.musicfx
				pm disable com.android.nfc
				pm disable com.android.printservice.recommendation
				pm disable com.android.printspooler
				pm disable com.android.providers.blockednumber
				pm disable com.android.providers.calendar
				pm disable com.android.screenshot
				pm disable com.android.stk
				pm disable com.android.theme.color.black
				pm disable com.android.theme.color.bluegray
				pm disable com.android.theme.color.cinnamon
				pm disable com.android.theme.color.cyan
				pm disable com.android.theme.color.flatpink
				pm disable com.android.theme.color.green
				pm disable com.android.theme.color.indigo
				pm disable com.android.theme.color.lightpurple
				pm disable com.android.theme.color.mint
				pm disable com.android.theme.color.ocean
				pm disable com.android.theme.color.orchid
				pm disable com.android.theme.color.pink
				pm disable com.android.theme.color.primary.black
				pm disable com.android.theme.color.primary.darkblue
				pm disable com.android.theme.color.purple
				pm disable com.android.theme.color.qgreen
				pm disable com.android.theme.color.space
				pm disable com.android.theme.color.teal
				pm disable com.android.theme.color.violet
				pm disable com.android.theme.color.yellow
				pm disable com.android.theme.font.arbutussource
				pm disable com.android.theme.font.arvolato
				pm disable com.android.theme.font.googlesans
				pm disable com.android.theme.font.notoserifsource
				pm disable com.android.theme.font.rubikrubik
				pm disable com.android.theme.icon.cylinder
				pm disable com.android.theme.icon.square
				pm disable com.android.theme.icon.teardrop
				pm disable com.android.theme.icon_pack.circular.android
				pm disable com.android.theme.icon_pack.circular.launcher
				pm disable com.android.theme.icon_pack.circular.settings
				pm disable com.android.theme.icon_pack.circular.systemui
				pm disable com.android.theme.icon_pack.circular.themepicker
				pm disable com.android.theme.icon_pack.filled.android
				pm disable com.android.theme.icon_pack.filled.launcher
				pm disable com.android.theme.icon_pack.filled.settings
				pm disable com.android.theme.icon_pack.filled.systemui
				pm disable com.android.theme.icon_pack.filled.themepicker
				pm disable com.android.wallpaper
				pm disable com.android.wallpaper.livepicker
				pm disable com.android.wallpaperbackup
				pm disable com.android.wallpapercropper
				pm disable com.cyanogenmod.pocketmode
				pm disable com.google.android.apps.photosgo
				pm disable com.google.android.apps.restore
				pm disable com.google.android.apps.wallpaper.nexus
				pm disable com.google.android.backuptransport
				pm disable com.google.android.feedback
				pm disable com.google.android.setupwizard
				pm disable com.google.android.soundpicker
				pm disable com.google.android.syncadapters.calendar
				pm disable com.google.android.syncadapters.contacts
				pm disable com.havoc.browser
				pm disable com.qualcomm.qti.biometrics.fingerprint.service
				pm disable com.qualcomm.qti.cne
				pm disable com.qualcomm.qti.uceShimService
				pm disable org.omnirom.omnistyle
				pm disable com.dsi.ant.server
				pm disable org.lineageos.settings.device
				pm disable com.google.android.tts
				pm disable com.android.dynsystem
				pm disable com.android.mms.service
				pm disable com.google.android.apps.customization.pixel
				pm disable org.simalliance.openmobileapi.service
				pm disable com.android.theme.icon.squircle
				pm disable com.google.android.apps.safetyhub
				;;
			2)
				clear
				echo "KIỂM TRA CẬP NHẬT ỨNG DỤNG"
				echo "1. AdGuard Premium"
				echo "2. Greenify Donate"
				echo "3. Titan Backup Pro"
				echo "4. Smartpack-Kernel Manager"
				echo "5. Youtube Vanced + MicroG"
				echo "6. Magisk + Module"
				echo "7. Open Gapps"
				echo "8. Google Clock"
				echo "9. Lawnchair"
				echo "10. X-plore Donate"
				echo "11. Webview Google"
				echo "12. Tất cả"
				echo "Nhập số từ 1-12 (nhấn x để thoát):"
				read app
				
				case $app in
					1)
						echo `date +"%l:%M:%S %p ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
						bash /sdcard/Download/ext/temp/adguard
						;;
					2)
						echo `date +"%l:%M:%S %p ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
						bash /sdcard/Download/ext/temp/greenify
						;;
					3)
						echo `date +"%l:%M:%S %p ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
						bash /sdcard/Download/ext/temp/titan
						;;
					4)
						echo `date +"%l:%M:%S %p ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
						bash /sdcard/Download/ext/temp/skm
						;;
					5)
						echo `date +"%l:%M:%S %p ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
						bash /sdcard/Download/ext/temp/youtube
						;;
					6)
						echo `date +"%l:%M:%S %p ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
						bash /sdcard/Download/ext/temp/magisk
						;;
					7)
						echo `date +"%l:%M:%S %p ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
						bash /sdcard/Download/ext/temp/opengapp
						;;
					8)
						echo `date +"%l:%M:%S %p ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
						bash /sdcard/Download/ext/temp/clock
						;;
					9)
						echo `date +"%l:%M:%S %p ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
						bash /sdcard/Download/ext/temp/lawnchair
						;;
					10)
						echo `date +"%l:%M:%S %p ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
						bash /sdcard/Download/ext/temp/xplore
						;;
					11)
						echo `date +"%l:%M:%S %p ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
						bash /sdcard/Download/ext/temp/webview
						;;
					12)
						echo `date +"%l:%M:%S %p ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
						bash /sdcard/Download/ext/temp/adguard
						bash /sdcard/Download/ext/temp/greenify
						bash /sdcard/Download/ext/temp/titan
						bash /sdcard/Download/ext/temp/youtube
						bash /sdcard/Download/ext/temp/skm
						bash /sdcard/Download/ext/temp/magisk
						bash /sdcard/Download/ext/temp/opengapp
						bash /sdcard/Download/ext/temp/clock
						bash /sdcard/Download/ext/temp/lawnchair
						bash /sdcard/Download/ext/temp/xplore
						bash /sdcard/Download/ext/temp/webview
						;;
					x)
						echo "Thoát!"
						;;
				esac
				;;
			x)
				echo "Thoát"
				;;
		esac
		bash /sdcard/Download/ext/temp/menu
		;;
	3)
		echo "Chạy profile kernel: battery"
		sh /sdcard/Download/ext/temp/battery
		bash /sdcard/Download/ext/temp/menu
		;;
	4)
		clear
		bash /sdcard/Download/ext/temp/kernel
		bash /sdcard/Download/ext/temp/menu
		;;
	5)
		clear
		bash /sdcard/Download/ext/temp/game
		bash /sdcard/Download/ext/temp/menu
		;;
	x)
		echo "Chạy profile kernel: battery"
		sh /sdcard/Download/ext/temp/battery
		find /sdcard/Download/ext/temp -type f -not -name 'log' -print0 | xargs -0 rm
		killall -9 com.termux
		;;
esac
