#!/data/data/com.termux/files/usr/bin/bash

path=`su -c "find /data/app -type d -name 'com.google.ar.core*'"`

if [ -z "$path" ]
then
	echo""
else
	echo "Gỡ cài đặt Google Play for AR Core"
	su -c "pm uninstall com.google.ar.core"
fi

clear
echo "Chọn công việc:"
echo "1. HoYo Lab"
echo "2. Hack data"
echo "3. Shopee"
echo "4. AdAway"
echo "5. Vietcombank"
echo "6. MoMo"
echo "7. Lazada"
echo "8. Google Drive"
echo "9. Quick Edit+"
echo "10. Mt Manager"
echo "11. Thoát"
echo "Nhập số từ 1-11:"
read choose

function enable+run {
	su -c "pm enable $package"
	su -c "am start --user 0 -n $package/$activity"
}
	
function disable {
	su -c "pm disable $package"
}

function hoyo_lab {
	echo "•Bạn chọn Hoyo Lab"
	package="com.mihoyo.hoyolab"
	activity="com.mihoyo.hoyolab.home.HoYoLabMainActivity"
}

function hack_data {
	echo "•Bạn chọn Hack Data"
	su -c "pm enable com.android.vpndialogs"
	echo 1 > /storage/emulated/0/Download/ext/temp/vpndialog
	package="com.github.kr328.clash"
	activity="com.github.kr328.clash.MainActivity"
	#package="com.v2ray.ang"
	#activity="com.v2ray.ang.ui.MainActivity"
}

function shoppe {
	echo "•Bạn chọn Shopee"
	package="com.shopee.vn"
	activity="com.shopee.app.ui.home.HomeActivity_"
}

function adaway {
	echo "•Bạn chọn AdAway"
	package="org.adaway"
	activity="org.adaway.ui.home.HomeActivity"
}

function VCB {
	echo "•Bạn chọn Vietcombank"
	package="com.VCB"
	activity="com.VCB.activities.home.SplashActivity"
}

function momo {
	echo "•Bạn chọn MoMo"
	package="com.mservice.momotransfer"
	activity="vn.momo.platform.MainActivity"
}

function lazada {
	echo "•Bạn chọn Lazada"
	package="com.lazada.android"
	activity="com.lazada.activities.EnterActivity"
}

function G_drive {
	echo "•Bạn chọn Google Drive"
	package="com.google.android.apps.docs"
	activity="com.google.android.apps.docs.drive.startup.StartupActivity"
}

function quick_edit {
	echo "•Bạn chọn Quick Edit+"
	package="com.rhmsoft.edit.pro"
	activity="com.rhmsoft.edit.activity.MainActivity"
}

function mtm {
	echo "•Bạn chọn Mt Manager"
	package="bin.mt.plus"
	activity="bin.mt.plus.Main"
}

function check_action {
	if [ $b = 1 ]
	then
		echo "•Bật và khởi chạy ứng dụng được chọn"
		enable+run
		rerun_ra
	elif [ $b = 2 ]
	then
		echo "•Tẵt ứng dụng được chọn"
		disable
		path=`su -c "find /storage/emulated/0/Download/ext/temp -type f -name 'vpndialog'"`
		if [ -z "$path" ]
		then
			echo ""
		else
			su -c "pm disable com.android.vpndialogs"
			rm -rf /storage/emulated/0/Download/ext/temp/vpndialog
		fi
		check_out
	fi
}

function check_out {
	if [ $c = 1 ]
	then
		rerun_ra
	elif [ $c = 0 ]
	then
		kill_termux
	fi
}

function rerun_ra {
	bash /storage/emulated/0/Download/ext/temp/ra
}

if [ $choose = 12345678910 ]
then
	for i in [ hoyo_lab hack_data shoppe adaway VCB momo lazada G_drive quick_edit mtm ]
	do
		$i
		enable+run
	done
	rerun_ra
fi

function kill_termux {
	su -c "killall -9 com.termux"
}
a=`echo $choose | cut -c 1-1`
b=`echo $choose | cut -c 2-2`
c=`echo $choose | cut -c 3-3`
d=`echo $choose | cut -c 4-4`

if [ $a = 1 ]
then
if [ $b = 0 ]
then
	mtm
	if [ $c = 1 ]
	then
		enable+run
		rerun_ra
	elif [ $c = 2 ]
	then
		disable
		if [ $d = 1 ]
		then
			rerun_ra
		elif [ $d = 0 ]
		then
			kill_termux
		fi
	fi
elif [ $b = 1 ]
then
	if [ -z "$c" ]
	then
		hoyo_lab
		enable+run
		rerun_ra
	else
		if [ $c = 1 ]
		then
			exit
		elif [ $c = 0 ]
		then
			kill_termux
		fi
	fi
elif [ $b = 2 ]
then
	hoyo_lab
disable
if [ $c = 1 ]
then
	rerun_ra
elif [ $c = 0 ]
then
	kill_termux
fi
fi
elif [ $a = 2 ]
then
	hack_data
	check_action
elif [ $a = 3 ]
then
	shoppe
	check_action
elif [ $a = 4 ]
then
	adaway
	check_action
elif [ $a = 5 ]
then
	VCB
	check_action
elif [ $a = 6 ]
then
	momo
	check_action
elif [ $a = 7 ]
then
	lazada
	check_action
elif [ $a = 8 ]
then
	G_drive
	check_action
elif [ $a = 9 ]
then
	quick_edit
	check_action
fi