#!/data/data/com.termux/files/usr/bin/bash

path=`su -c "find /data/app -type d -name 'com.google.ar.core*'"`

if [ -z "$path" ]
then
      echo""
else
      su -c "pm uninstall com.google.ar.core"
fi

clear
echo "Chọn công việc:"
echo "1. HoYo Lab"
echo "2. Hack data"
echo "3. Shopee"
echo "4. AdAway"
echo "5. Vietcombank"
echo "6. MoMo"
echo "7. Lazada"
echo "8. Google Drive"
echo "9. Quick Edit+"
echo "10. Mt Manager"
echo "11. Thoát"
echo "Nhập số từ 1-9:"
read choose

if [[ $choose = 111 || $choose = 110 ]]
then
	a=`echo $choose | cut -c 3-3`
	if [ $a = 1 ]
	then
		echo "•Thoát script."
		exit
	elif [ $a = 0 ]
	then
		su -c "killall -9 com.termux"
	fi
else
	num=`echo $choose | wc -c`
	if [[ $num = 3 || $num = 4 ]]
	then
	a=`echo $choose | cut -c 1-1`
	b=`echo $choose | cut -c 2-2`
	c=`echo $choose | cut -c 3-3`
	elif [ $num = 5 ]
	then
	a=`echo $choose | cut -c 1-2`
	b=`echo $choose | cut -c 3-3`
	c=`echo $choose | cut -c 4-4`
	fi
fi

function enable+run {
	su -c "pm enable $package"
	su -c "am start --user 0 -n $package/$activity"
}
	
function disable {
	su -c "pm disable $package"
}

function check_c {
	if [ $c = 1 ]
	then
		bash /storage/emulated/0/Download/ext/temp/ra
	elif [ $c = 0 ]
	then
		su -c "killall -9 com.termux"
	fi
}

function check_b {
	if [ $b = 1 ]
	then
		echo "•Bật và khởi chạy ứng dụng được chọn"
		enable+run
		bash /storage/emulated/0/Download/ext/temp/ra
	elif [ $b = 2 ]
	then
		echo "•Tẵt ứng dụng được chọn"
		disable
		path=`su -c "find /storage/emulated/0/Download/ext/temp -type f -name 'vpndialog'"`
		if [ -z "$path" ]
		then
			echo ""
		else
			su -c "pm disable com.android.vpndialogs"
			rm -rf /storage/emulated/0/Download/ext/temp/vpndialog
		fi
		check_c
	fi
}

if [ $a = 1 ]
then
	echo "•Bạn chọn Hoyo Lab"
	package="com.mihoyo.hoyolab"
	activity="com.mihoyo.hoyolab.home.HoYoLabMainActivity"
	check_b
elif [ $a = 2 ]
then
	echo "•Bạn chọn Hack Data"
	su -c "pm enable com.android.vpndialogs"
	echo 1 > /storage/emulated/0/Download/ext/temp/vpndialog
	package="com.github.kr328.clash"
	activity="com.github.kr328.clash.MainActivity"
	#package="com.v2ray.ang"
	#activity="com.v2ray.ang.ui.MainActivity"
	check_b
elif [ $a = 3 ]
then
	echo "•Bạn chọn Shopee"
	package="com.shopee.vn"
	activity="com.shopee.app.ui.home.HomeActivity_"
	check_b
elif [ $a = 4 ]
then
	echo "•Bạn chọn AdAway"
	package="org.adaway"
	activity="org.adaway.ui.home.HomeActivity"
	check_b
elif [ $a = 5 ]
then
	echo "•Bạn chọn Vietcombank"
	package="com.VCB"
	activity="com.VCB.activities.home.SplashActivity"
	check_b
elif [ $a = 6 ]
then
	echo "•Bạn chọn MoMo"
	package="com.mservice.momotransfer"
	activity="vn.momo.platform.MainActivity"
	check_b
elif [ $a = 7 ]
then
	echo "•Bạn chọn Lazada"
	package="com.lazada.android"
	activity="com.lazada.activities.EnterActivity"
	check_b
elif [ $a = 8 ]
then
	echo "•Bạn chọn Google Drive"
	package="com.google.android.apps.docs"
	activity="com.google.android.apps.docs.drive.startup.StartupActivity"
	check_b
elif [ $a = 9 ]
then
	echo "•Bạn chọn Quick Edit+"
	package="com.rhmsoft.edit.pro"
	activity="com.rhmsoft.edit.activity.MainActivity"
	check_b
elif [ $a = 10 ]
then
	echo "•Bạn chọn Mt Manager"
	package="bin.mt.plus"
	activity="bin.mt.plus.Main"
	check_b
fi