#!/data/data/com.termux/files/usr/bin/bash

rm /sdcard/Download/ext/temp/a 2>/dev/null

wget -O - https://github.com/YTVanced/VancedManager/releases > /sdcard/Download/ext/temp/a
cat /sdcard/Download/ext/temp/a | grep "YTVanced/VancedManager/releases/download" > /sdcard/Download/ext/temp/aa
read -r version_web < /sdcard/Download/ext/temp/aa
a=`echo $version_web | perl -pe 'if(($_)=/([0-9]+([.][0-9]+)+)/){$_.="\n"}' | awk '{if ($1 > max) max=$1}END{print max}'`

clear
echo "••Phiên bản Youtube Vanced Manager hiện tại: $a"
echo "••Bạn có muốn tải xuống?"
echo "1. Có"
echo "2. Không"
read ytmanager

case $ytmanager in
1)
   download_link=https://github.com/YTVanced/VancedManager/releases/download/v$a/manager.apk
   wget --no-check-certificate  -P /sdcard "$download_link"
;;
2)
   clear
;;
esac

echo `date +"%r, thứ %a, ngày %d, tháng %m, năm %Y"` >> /sdcard/Download/ext/temp/log
echo "•Youtube Vanced Manager: $a" >> /storage/emulated/0/Download/ext/temp/log

sed -i 's/ PM / CH /g' /storage/emulated/0/Download/ext/temp/log
sed -i 's/ AM / SA /g' /storage/emulated/0/Download/ext/temp/log
sed -i 's/ Mon, / Hai, /g' /storage/emulated/0/Download/ext/temp/log
sed -i 's/ Tue, / Ba, /g' /storage/emulated/0/Download/ext/temp/log
sed -i 's/ Wed, / Tư, /g' /storage/emulated/0/Download/ext/temp/log
sed -i 's/ Thur, / Năm, /g' /storage/emulated/0/Download/ext/temp/log
sed -i 's/ Fri, / Sáu, /g' /storage/emulated/0/Download/ext/temp/log
sed -i 's/ Sat, / Bảy, /g' /storage/emulated/0/Download/ext/temp/log
sed -i 's/ Sun, / Chủ nhật, /g' /storage/emulated/0/Download/ext/temp/log

rm /sdcard/Download/ext/temp/a 2>/dev/null